### ISSUE TITLE
Client/Server Desync (Tiles)

### ISSUE THREAD

**Issue by Blanketeer-X** [Arrenton/Leveled#12] opened 2019-01-06 20:02 UTC
Tiles broken on client side occasionally does not register to the server side, and not get the tile after mining it. Was noticed on the beta server.

- Consistent
- Beta

Good examples is two pictures:

![ss 2019-01-06 at 12 35 07](https://user-images.githubusercontent.com/24882034/50740866-c8aad300-11b2-11e9-8fde-7f74514821e4.png)
On the beta server:
![ss 2019-01-06 at 12 23 03](https://user-images.githubusercontent.com/24882034/50740867-c8aad300-11b2-11e9-942c-a896e0889f64.png)

Both of these are from reconnecting after clearing out a section, but it's noticeable when ya don't get blocks for a bit during the mining.

v1.0.0.20

**Comment by webmilio** [comment] 2019-02-17 03:00
Unable to reproduce issue. The only thing we found while trying to reproduce it was a lot of MessageBuffer errors when using dynamite. Closing for now.

**Closed as completed by webmilio** 2019-02-17 03:00 UTC
Labels: bug, beta, on hold
